In [1]:
import numpy as np
import pandas as pd

In [2]:
def fitness_eval(p):
    return -5*p*p + 1000*p

In [3]:
def initial_population(size,constraints):
    low,high=constraints
    population=np.random.randint(low,high,size)
    return population

In [4]:
def parent_selection(population,chromosomes):
    population_fitness=np.array([fitness_eval(x) for x in population])
    print("population fitness =",population_fitness)
    total_fitness=np.sum(population_fitness)
    print("total fitness =",total_fitness)
    fitness_probability=population_fitness/total_fitness
    print("fitness probability =",fitness_probability)
    cummulative_wheel=np.cumsum(fitness_probability)
    print("cummulative wheel =",cummulative_wheel)
    # Generating random values of probability for chromosomes using roulette wheel
    random_chromosome_probab=np.random.uniform(0,1,size=chromosomes)
    print("random chromosomes probability =",random_chromosome_probab)
    #finding index of random chromosomes
    chromosome_index=np.searchsorted(cummulative_wheel,random_chromosome_probab)
    print("chromosome index =",chromosome_index)
    parent_selected=np.array([population[x] for x in chromosome_index])
    return parent_selected

In [5]:
population1=initial_population(6,(50,200))
population2=initial_population(6,(50,200))
population1,population2

(array([173, 157, 160,  65,  53,  80]), array([ 59, 136, 165,  53,  57, 126]))

In [6]:
parent1=parent_selection(population1,6)
parent2=parent_selection(population2,6)
parent1,parent2

population fitness = [23355 33755 32000 43875 38955 48000]
total fitness = 219940
fitness probability = [0.10618805 0.15347367 0.14549423 0.19948622 0.17711649 0.21824134]
cummulative wheel = [0.10618805 0.25966173 0.40515595 0.60464218 0.78175866 1.        ]
random chromosomes probability = [0.20781779 0.2556162  0.32393753 0.7579068  0.42674246 0.36352993]
chromosome index = [1 1 2 4 3 2]
population fitness = [41595 43520 28875 38955 40755 46620]
total fitness = 240320
fitness probability = [0.17308172 0.18109188 0.1201523  0.16209637 0.16958638 0.19399134]
cummulative wheel = [0.17308172 0.3541736  0.4743259  0.63642227 0.80600866 1.        ]
random chromosomes probability = [0.2453447  0.10311304 0.39155422 0.17026274 0.27198978 0.24863653]
chromosome index = [1 0 2 0 1 1]


(array([157, 157, 160,  53,  65, 160]), array([136,  59, 165,  59, 136, 136]))

In [7]:
def crossover_participent(parent,crossover_parameter):
    n=round(crossover_parameter*len(parent))
    selected_parents=np.random.choice(parent,n,replace=False)
#     print("parents selected for crossover =",selected_parents)
    return selected_parents
    

In [30]:
def crossover(parent1, parent2, min_value, max_value):
    # Initialize offspring arrays
    offspring1 = np.zeros_like(parent1)
    offspring2 = np.zeros_like(parent2)
    
    # Perform crossover for each element in the parent arrays
    for i in range(len(parent1)):
        # Randomly select a value between the corresponding elements in the parent arrays
        if(parent1[i]==parent2[i]):
            value1=parent1[i]
            value2=parent1[i]
        else:
            value1 = np.random.randint(min(parent1[i], parent2[i]), max(parent1[i], parent2[i]))
            value2 = np.random.randint(min(parent1[i], parent2[i]), max(parent1[i], parent2[i]))
        
        # Ensure that the selected values are within the given range
        value1 = min(max(value1, min_value), max_value)
        value2 = min(max(value2, min_value), max_value)
        
        # Add the selected values to the offspring arrays
        offspring1[i] = value1
        offspring2[i] = value2
    
    return offspring1, offspring2

In [9]:
parent1=crossover_participent(parent1,1)
parent2=crossover_participent(parent2,1)
parent1,parent2

(array([157, 160,  65, 157, 160,  53]), array([136,  59, 136,  59, 136, 165]))

In [10]:
offspring1,offspring2=crossover(parent1,parent2,50,200)

In [11]:
offspring1,offspring2

(array([156,  84,  71, 101, 143,  95]), array([144, 128, 104,  62, 145,  95]))

In [12]:
offsprings=np.concatenate((offspring1,offspring2),axis=None)
offsprings

array([156,  84,  71, 101, 143,  95, 144, 128, 104,  62, 145,  95])

In [13]:
def mutation(offsprings,bit_position):
    bit_mask=1<<bit_position
    offsprings^=bit_mask
    return offsprings

In [14]:
mutated_offsprings=mutation(offsprings,2)
mutated_offsprings

array([152,  80,  67,  97, 139,  91, 148, 132, 108,  58, 149,  91])

In [15]:
offsprings_fitness=np.array([fitness_eval(x) for x in mutated_offsprings])
offsprings_fitness

array([36480, 48000, 44555, 49955, 42395, 49595, 38480, 44880, 49680,
       41180, 37995, 49595])

In [16]:
def make_population(offsprings):
    # randomly shuffle the indices of the array
    shuffled_indices = np.random.permutation(offsprings.shape[0])

    # split the array into two parts using the shuffled indices
    split_index = int(offsprings.shape[0] / 2)
    arr1 = offsprings[shuffled_indices[:split_index]]
    arr2 = offsprings[shuffled_indices[split_index:]]
    return arr1,arr2

In [25]:
def geneticAlgo(population1,population2,n):
    mutated_offspirngs=[]
    for i in range(n):
        print("population1 =",population1)
        print("population2 =",population2)
        print()
        parent1=parent_selection(population1,6)
        parent2=parent_selection(population2,6)
        print("selected parent 1=",parent1)
        print("selected parent 2=",parent2)
        print()
#         parent1=crossover_participent(parent1,1)
#         parent2=crossover_participent(parent2,1)
#         print("crossovered parent 1=",parent1)
#         print("crossovered parent 2=",parent2)
#         print()
        offspring1,offspring2=crossover(parent1,parent2,50,200)
        print("offspirng1 =",offspring1)
        print("offspring2 =",offspring2)
        print()
        offsprings=np.concatenate((offspring1,offspring2),axis=None)
        print("offsprings =",offsprings)
        print()
        mutated_offsprings=mutation(offsprings,2)
        print("mutated_offsprings =",mutated_offsprings)
        print()
        population1,population2=make_population(mutated_offsprings)
    
    return mutated_offsprings
    


In [31]:
population1=initial_population(6,(50,200))
population2=initial_population(6,(50,200))
mutated_offsprings=geneticAlgo(population1,population2,5)
offsprings_fitness=np.array([fitness_eval(x) for x in mutated_offsprings])
print("Final Population Finess",offsprings_fitness)
# print("fittest indivisual =")

population1 = [108 173 126  97 131 106]
population2 = [127 169 191 143  67 101]

population fitness = [49680 23355 46620 49955 45195 49820]
total fitness = 264625
fitness probability = [0.18773736 0.08825697 0.17617383 0.18877657 0.17078885 0.18826641]
cummulative wheel = [0.18773736 0.27599433 0.45216816 0.64094473 0.81173359 1.        ]
random chromosomes probability = [0.94689833 0.36939945 0.07224521 0.98721221 0.89354328 0.77874816]
chromosome index = [5 2 0 5 5 4]
population fitness = [46355 26195  8595 40755 44555 49995]
total fitness = 216450
fitness probability = [0.21416031 0.12102102 0.03970894 0.18828829 0.20584431 0.23097713]
cummulative wheel = [0.21416031 0.33518134 0.37489027 0.56317856 0.76902287 1.        ]
random chromosomes probability = [0.78323036 0.42038485 0.06676741 0.49597854 0.93147029 0.93689624]
chromosome index = [5 3 0 3 5 5]
selected parent 1= [106 126 108 106 106 131]
selected parent 2= [101 143 127 143 101 101]

offspirng1 = [105 139 123 136 105 115]
o

In [32]:
fittest_offspring=-1
fitness_value=0
for i in range(10):
    if(offsprings_fitness[i]>fitness_value):
        fittest_offspirng=mutated_offsprings[i]
        fitness_value=offsprings_fitness[i]
print(f"Fittest Offspring is :{fittest_offspirng} with value {fitness_value}")

Fittest Offspring is :115 with value 48875
